services:
  simulideservice:
    image: simulideservice
    build:
      context: .
      dockerfile: SimulideService/Dockerfile
    depends_on:
      - simulide-db
    ports:
        - "8080:8080"
    networks:
        - simulide-net
  simulide-db:
    image: postgres:14.6-alpine
    restart: always
    ports:
        - "5432:5432"
    environment:
      POSTGRES_USER: simulide
      POSTGRES_PASSWORD: simulide
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
        - simulide-net
volumes:
    db:
      driver: local
  
networks:
    simulide-net:
      driver: bridge
